function reorganizar_projeto_final()
    % ========================================================================
    % REORGANIZAR_PROJETO_FINAL - Limpeza e Organização Final do Projeto
    % ========================================================================
    % 
    % DESCRIÇÃO:
    %   Script para limpar arquivos obsoletos e reorganizar a estrutura final
    %   do projeto Sistema de Comparação U-Net vs Attention U-Net
    %
    % AUTOR: Sistema de Comparação U-Net vs Attention U-Net
    % Data: Julho 2025
    % ========================================================================
    
    fprintf('🧹 REORGANIZAÇÃO FINAL DO PROJETO\n');
    fprintf('=================================\n\n');
    
    try
        % 1. Criar estrutura de diretórios necessária
        criarEstruturaDiretorios();
        
        % 2. Mover arquivos para pastas corretas
        moverArquivosParaPastas();
        
        % 3. Remover arquivos obsoletos
        removerArquivosObsoletos();
        
        % 4. Criar arquivo principal de execução
        criarArquivoPrincipal();
        
        % 5. Atualizar documentação
        atualizarDocumentacao();
        
        fprintf('✅ Reorganização concluída com sucesso!\n');
        fprintf('\n📋 COMO USAR O SISTEMA:\n');
        fprintf('1. Execute: main_sistema_comparacao\n');
        fprintf('2. Siga as instruções do menu interativo\n');
        fprintf('3. Para ajuda: consulte docs/COMO_USAR.md\n\n');
        
    catch ME
        fprintf('❌ Erro na reorganização: %s\n', ME.message);
        rethrow(ME);
    end
end

function criarEstruturaDiretorios()
    % Criar estrutura de diretórios necessária
    
    fprintf('📁 Criando estrutura de diretórios...\n');
    
    diretorios = {
        'scripts'           % Scripts auxiliares
        'utils'             % Utilitários gerais
        'legacy'            % Arquivos antigos (para backup)
        'validation'        % Scripts de validação
        'examples'          % Exemplos de uso
        'config/templates'  % Templates de configuração
    };
    
    for i = 1:length(diretorios)
        if ~exist(diretorios{i}, 'dir')
            mkdir(diretorios{i});
            fprintf('  ✓ Criado: %s\n', diretorios{i});
        end
    end
end

function moverArquivosParaPastas()
    % Mover arquivos para suas pastas corretas
    
    fprintf('\n📦 Movendo arquivos para pastas corretas...\n');
    
    % Scripts auxiliares para pasta scripts/
    scripts_auxiliares = {
        'configuracao_inicial_automatica.m'
        'configurar_caminhos.m'
        'criar_estrutura_diretorios.m'
        'install_system.m'
        'migrate_system.m'
        'testar_configuracao.m'
        'verificar_diretorios.m'
        'inicio_rapido.m'
        'exportar_configuracao_portatil.m'
    };
    
    for i = 1:length(scripts_auxiliares)
        arquivo = scripts_auxiliares{i};
        if exist(arquivo, 'file')
            movefile(arquivo, fullfile('scripts', arquivo));
            fprintf('  ✓ Movido: %s → scripts/\n', arquivo);
        end
    end
    
    % Scripts de validação para pasta validation/
    scripts_validacao = {
        'simple_validation.m'
        'simple_performance_validation.m'
        'validate_comparison_controller.m'
        'validate_config_manager.m'
        'validate_performance_optimizations.m'
        'validate_system_consistency.m'
        'validate_visualization_system.m'
        'verificacao_final_projeto.m'
        'test_comparison_controller.m'
        'test_config_manager.m'
        'test_main_interface.m'
    };
    
    for i = 1:length(scripts_validacao)
        arquivo = scripts_validacao{i};
        if exist(arquivo, 'file')
            movefile(arquivo, fullfile('validation', arquivo));
            fprintf('  ✓ Movido: %s → validation/\n', arquivo);
        end
    end
    
    % Utilitários para pasta utils/
    utils_files = {
        'analisar_mascaras_automatico.m'
        'analise_metricas_detalhada.m'
        'calcular_accuracy_simples.m'
        'calcular_dice_simples.m'
        'calcular_iou_simples.m'
        'carregar_dados_robustos.m'
        'converter_mascaras.m'
        'gerar_relatorio_final.m'
        'preprocessDataCorrigido.m'
        'preprocessDataMelhorado.m'
        'treinar_unet_simples.m'
    };
    
    for i = 1:length(utils_files)
        arquivo = utils_files{i};
        if exist(arquivo, 'file')
            movefile(arquivo, fullfile('utils', arquivo));
            fprintf('  ✓ Movido: %s → utils/\n', arquivo);
        end
    end
    
    % Arquivos legados para pasta legacy/
    legacy_files = {
        'comparacao_unet_attention_final.m'
        'create_working_attention_unet.m'
        'executar_testes_completos.m'
        'remover_arquivos_obsoletos.m'
    };
    
    for i = 1:length(legacy_files)
        arquivo = legacy_files{i};
        if exist(arquivo, 'file')
            movefile(arquivo, fullfile('legacy', arquivo));
            fprintf('  ✓ Movido: %s → legacy/\n', arquivo);
        end
    end
end

function removerArquivosObsoletos()
    % Remover arquivos que não são mais necessários
    
    fprintf('\n🗑️  Removendo arquivos obsoletos...\n');
    
    arquivos_obsoletos = {
        'config_caminhos.mat'           % Substituído por ConfigManager
        'relatorio_comparacao.txt'      % Será gerado automaticamente
        'comparacao_visual_modelos.png' % Será gerado automaticamente
    };
    
    for i = 1:length(arquivos_obsoletos)
        arquivo = arquivos_obsoletos{i};
        if exist(arquivo, 'file')
            delete(arquivo);
            fprintf('  ✓ Removido: %s\n', arquivo);
        end
    end
end

function criarArquivoPrincipal()
    % Criar arquivo principal de execução
    
    fprintf('\n📝 Criando arquivo principal de execução...\n');
    
    conteudo_main = [
        'function main_sistema_comparacao()\n'...
        '    % ========================================================================\n'...
        '    % MAIN_SISTEMA_COMPARACAO - Arquivo Principal do Sistema\n'...
        '    % ========================================================================\n'...
        '    % \n'...
        '    % DESCRIÇÃO:\n'...
        '    %   Arquivo principal para executar o Sistema de Comparação U-Net vs\n'...
        '    %   Attention U-Net. Este é o ponto de entrada único do sistema.\n'...
        '    %\n'...
        '    % COMO USAR:\n'...
        '    %   >> main_sistema_comparacao\n'...
        '    %\n'...
        '    % REQUISITOS:\n'...
        '    %   - MATLAB R2019b ou superior\n'...
        '    %   - Deep Learning Toolbox\n'...
        '    %   - Image Processing Toolbox\n'...
        '    %\n'...
        '    % AUTOR: Sistema de Comparação U-Net vs Attention U-Net\n'...
        '    % Data: Julho 2025\n'...
        '    % Versão: 3.0 - Performance Optimization\n'...
        '    % ========================================================================\n'...
        '    \n'...
        '    try\n'...
        '        % Verificar se estamos no diretório correto\n'...
        '        if ~exist(''src'', ''dir'')\n'...
        '            error(''Execute este script a partir do diretório raiz do projeto!'');\n'...
        '        end\n'...
        '        \n'...
        '        % Adicionar caminhos necessários\n'...
        '        addpath(genpath(''src''));\n'...
        '        addpath(genpath(''scripts''));\n'...
        '        addpath(genpath(''utils''));\n'...
        '        \n'...
        '        % Exibir informações do sistema\n'...
        '        fprintf(''\\n🚀 SISTEMA DE COMPARAÇÃO U-NET vs ATTENTION U-NET\\n'');\n'...
        '        fprintf(''=====================================================\\n'');\n'...
        '        fprintf(''Versão: 3.0 - Performance Optimization\\n'');\n'...
        '        fprintf(''Data: %s\\n'', datestr(now, ''dd/mm/yyyy HH:MM''));\n'...
        '        fprintf(''MATLAB: %s\\n'', version);\n'...
        '        fprintf(''=====================================================\\n\\n'');\n'...
        '        \n'...
        '        % Verificar dependências básicas\n'...
        '        verificarDependencias();\n'...
        '        \n'...
        '        % Criar e executar interface principal\n'...
        '        interface = MainInterface();\n'...
        '        interface.run();\n'...
        '        \n'...
        '    catch ME\n'...
        '        fprintf(''❌ Erro ao executar sistema: %s\\n'', ME.message);\n'...
        '        fprintf(''\\n💡 Dicas:\\n'');\n'...
        '        fprintf(''1. Verifique se está no diretório correto\\n'');\n'...
        '        fprintf(''2. Verifique se as toolboxes estão instaladas\\n'');\n'...
        '        fprintf(''3. Consulte docs/COMO_USAR.md para mais ajuda\\n\\n'');\n'...
        '        rethrow(ME);\n'...
        '    end\n'...
        'end\n'...
        '\n'...
        'function verificarDependencias()\n'...
        '    % Verificar dependências básicas\n'...
        '    \n'...
        '    toolboxes_necessarias = {\n'...
        '        ''Deep Learning Toolbox'', ''Neural_Network_Toolbox'';\n'...
        '        ''Image Processing Toolbox'', ''Image_Toolbox'';\n'...
        '    };\n'...
        '    \n'...
        '    fprintf(''🔍 Verificando dependências...\\n'');\n'...
        '    \n'...
        '    for i = 1:size(toolboxes_necessarias, 1)\n'...
        '        nome = toolboxes_necessarias{i, 1};\n'...
        '        licenca = toolboxes_necessarias{i, 2};\n'...
        '        \n'...
        '        if license(''test'', licenca)\n'...
        '            fprintf(''  ✅ %s: OK\\n'', nome);\n'...
        '        else\n'...
        '            fprintf(''  ❌ %s: NÃO ENCONTRADA\\n'', nome);\n'...
        '            warning(''Toolbox não encontrada: %s'', nome);\n'...
        '        end\n'...
        '    end\n'...
        '    \n'...
        '    fprintf(''\\n'');\n'...
        'end\n'
    ];
    
    % Escrever arquivo principal
    fid = fopen('main_sistema_comparacao.m', 'w');
    if fid == -1
        error('Não foi possível criar arquivo principal');
    end
    fprintf(fid, '%s', conteudo_main);
    fclose(fid);
    
    fprintf('  ✓ Criado: main_sistema_comparacao.m\n');
end

function atualizarDocumentacao()
    % Atualizar documentação com instruções de uso
    
    fprintf('\n📚 Atualizando documentação...\n');
    
    % Criar guia de como usar
    criarGuiaComoUsar();
    
    % Atualizar README principal
    atualizarREADME();
    
    fprintf('  ✓ Documentação atualizada\n');
end

function criarGuiaComoUsar()
    % Criar guia detalhado de como usar o sistema
    
    conteudo_guia = [
        '# Como Usar o Sistema de Comparação U-Net vs Attention U-Net\n\n'...
        '## 🚀 Início Rápido\n\n'...
        '### 1. Execução Simples\n'...
        '```matlab\n'...
        '% No MATLAB, navegue até o diretório do projeto e execute:\n'...
        'main_sistema_comparacao\n'...
        '```\n\n'...
        '### 2. Primeira Execução\n'...
        '1. **Prepare seus dados**: Coloque imagens em `img/original/` e máscaras em `img/masks/`\n'...
        '2. **Execute o sistema**: `main_sistema_comparacao`\n'...
        '3. **Escolha opção 1**: "Execução Rápida" para teste inicial\n'...
        '4. **Aguarde**: O sistema executará automaticamente\n\n'...
        '## 📁 Estrutura do Projeto\n\n'...
        '```\n'...
        'projeto/\n'...
        '├── main_sistema_comparacao.m    # 🚀 ARQUIVO PRINCIPAL - EXECUTE ESTE\n'...
        '├── src/                         # Código fonte principal\n'...
        '│   ├── core/                    # Classes principais\n'...
        '│   ├── data/                    # Carregamento e processamento\n'...
        '│   ├── models/                  # Arquiteturas de rede\n'...
        '│   ├── evaluation/              # Métricas e avaliação\n'...
        '│   ├── visualization/           # Gráficos e relatórios\n'...
        '│   └── utils/                   # Utilitários do sistema\n'...
        '├── img/                         # Seus dados\n'...
        '│   ├── original/                # 📸 COLOQUE SUAS IMAGENS AQUI\n'...
        '│   └── masks/                   # 🎭 COLOQUE SUAS MÁSCARAS AQUI\n'...
        '├── output/                      # Resultados (criado automaticamente)\n'...
        '├── docs/                        # Documentação completa\n'...
        '├── scripts/                     # Scripts auxiliares\n'...
        '├── utils/                       # Utilitários gerais\n'...
        '├── validation/                  # Scripts de validação\n'...
        '└── examples/                    # Exemplos de uso\n'...
        '```\n\n'...
        '## 🎯 Opções do Menu Principal\n\n'...
        '### 1. 🚀 Execução Rápida\n'...
        '- **Para**: Iniciantes, teste rápido\n'...
        '- **Tempo**: 5-15 minutos\n'...
        '- **Dados**: 10% do dataset\n'...
        '- **Ideal para**: Primeira execução, validação dos dados\n\n'...
        '### 2. ⚙️ Configurar Dados e Parâmetros\n'...
        '- **Para**: Configuração personalizada\n'...
        '- **Permite**: Ajustar caminhos, parâmetros de treinamento\n'...
        '- **Ideal para**: Datasets em locais diferentes\n\n'...
        '### 3. 🔬 Comparação Completa\n'...
        '- **Para**: Análise detalhada\n'...
        '- **Tempo**: 30-120 minutos\n'...
        '- **Dados**: Dataset completo\n'...
        '- **Ideal para**: Resultados finais, publicação\n\n'...
        '### 4. 📊 Validação Cruzada K-Fold\n'...
        '- **Para**: Validação robusta\n'...
        '- **Tempo**: 2-8 horas\n'...
        '- **Dados**: Dataset completo, múltiplas divisões\n'...
        '- **Ideal para**: Pesquisa científica, máxima confiabilidade\n\n'...
        '## 📊 Interpretando Resultados\n\n'...
        '### Métricas Principais\n'...
        '- **IoU (Intersection over Union)**: 0-1, maior é melhor (>0.7 = bom)\n'...
        '- **Dice Coefficient**: 0-1, maior é melhor (>0.8 = bom)\n'...
        '- **Pixel Accuracy**: 0-100%, maior é melhor (>90% = bom)\n\n'...
        '### Arquivos de Resultado\n'...
        '- `output/reports/`: Relatórios detalhados\n'...
        '- `output/models/`: Modelos treinados\n'...
        '- `output/visualizations/`: Gráficos e comparações visuais\n\n'...
        '## 🔧 Solução de Problemas\n\n'...
        '### Erro: "Dados não encontrados"\n'...
        '1. Verifique se as imagens estão em `img/original/`\n'...
        '2. Verifique se as máscaras estão em `img/masks/`\n'...
        '3. Use a opção 2 do menu para configurar caminhos\n\n'...
        '### Erro: "Memória insuficiente"\n'...
        '1. Use a opção 1 (Execução Rápida) primeiro\n'...
        '2. Feche outros programas\n'...
        '3. O sistema tem otimizações automáticas de memória\n\n'...
        '### Erro: "Toolbox não encontrada"\n'...
        '1. Instale Deep Learning Toolbox\n'...
        '2. Instale Image Processing Toolbox\n'...
        '3. Verifique com: `ver`\n\n'...
        '## 📞 Ajuda Adicional\n\n'...
        '- **Menu de Ajuda**: Opção 7 no menu principal\n'...
        '- **Documentação Completa**: `docs/user_guide.md`\n'...
        '- **API Reference**: `docs/api_reference.md`\n'...
        '- **Validação do Sistema**: Execute `validation/simple_validation.m`\n\n'...
        '## 🎯 Dicas de Performance\n\n'...
        '### Para Datasets Grandes\n'...
        '- O sistema usa lazy loading automaticamente\n'...
        '- Cache inteligente otimiza processamento\n'...
        '- Monitoramento automático de recursos\n\n'...
        '### Para Máxima Velocidade\n'...
        '- Use GPU se disponível (detectado automaticamente)\n'...
        '- Sistema usa processamento paralelo quando possível\n'...
        '- Otimizações de memória são automáticas\n\n'...
        '---\n\n'...
        '**Versão**: 3.0 - Performance Optimization  \n'...
        '**Data**: Julho 2025  \n'...
        '**Compatibilidade**: MATLAB R2019b+\n'
    ];
    
    % Escrever guia
    fid = fopen('docs/COMO_USAR.md', 'w');
    if fid == -1
        error('Não foi possível criar guia de uso');
    end
    fprintf(fid, '%s', conteudo_guia);
    fclose(fid);
end

function atualizarREADME()
    % Atualizar README principal com instruções claras
    
    conteudo_readme = [
        '# Sistema de Comparação U-Net vs Attention U-Net\n\n'...
        '## 🚀 Início Rápido\n\n'...
        '### Execute em 3 passos:\n\n'...
        '1. **Prepare os dados**:\n'...
        '   - Coloque suas imagens em: `img/original/`\n'...
        '   - Coloque suas máscaras em: `img/masks/`\n\n'...
        '2. **Execute o sistema**:\n'...
        '   ```matlab\n'...
        '   main_sistema_comparacao\n'...
        '   ```\n\n'...
        '3. **Escolha a opção 1** no menu para execução rápida\n\n'...
        '## 📋 Requisitos\n\n'...
        '- MATLAB R2019b ou superior\n'...
        '- Deep Learning Toolbox\n'...
        '- Image Processing Toolbox\n'...
        '- Mínimo 4GB RAM (recomendado: 8GB+)\n\n'...
        '## 🎯 Características\n\n'...
        '- ✅ **Totalmente Automatizado**: Execute com um comando\n'...
        '- ✅ **Análise Estatística**: Testes de significância\n'...
        '- ✅ **Otimizado**: Lazy loading, cache inteligente\n'...
        '- ✅ **Monitoramento**: Recursos em tempo real\n'...
        '- ✅ **Portável**: Funciona em qualquer sistema\n\n'...
        '## 📊 Resultados\n\n'...
        'O sistema compara duas arquiteturas:\n'...
        '- **U-Net Clássica**: Encoder-decoder com skip connections\n'...
        '- **Attention U-Net**: U-Net com mecanismos de atenção\n\n'...
        'Métricas calculadas:\n'...
        '- IoU (Intersection over Union)\n'...
        '- Dice Coefficient\n'...
        '- Pixel Accuracy\n'...
        '- Análise estatística completa\n\n'...
        '## 📁 Estrutura\n\n'...
        '```\n'...
        'main_sistema_comparacao.m  ← 🚀 EXECUTE ESTE ARQUIVO\n'...
        'src/                       ← Código fonte\n'...
        'img/original/              ← 📸 SUAS IMAGENS AQUI\n'...
        'img/masks/                 ← 🎭 SUAS MÁSCARAS AQUI\n'...
        'output/                    ← Resultados automáticos\n'...
        'docs/                      ← Documentação completa\n'...
        '```\n\n'...
        '## 🔧 Solução Rápida de Problemas\n\n'...
        '| Problema | Solução |\n'...
        '|----------|----------|\n'...
        '| "Dados não encontrados" | Coloque imagens em `img/original/` e máscaras em `img/masks/` |\n'...
        '| "Memória insuficiente" | Use opção 1 (Execução Rápida) primeiro |\n'...
        '| "Toolbox não encontrada" | Instale Deep Learning Toolbox e Image Processing Toolbox |\n\n'...
        '## 📚 Documentação\n\n'...
        '- **[Como Usar](docs/COMO_USAR.md)**: Guia passo a passo\n'...
        '- **[Guia do Usuário](docs/user_guide.md)**: Documentação completa\n'...
        '- **[API Reference](docs/api_reference.md)**: Referência técnica\n\n'...
        '## 🎯 Versão Atual\n\n'...
        '**Versão 3.0 - Performance Optimization**\n'...
        '- Lazy loading para datasets grandes\n'...
        '- Cache inteligente de dados\n'...
        '- Monitoramento automático de recursos\n'...
        '- Identificação automática de gargalos\n'...
        '- Interface unificada e intuitiva\n\n'...
        '---\n\n'...
        '**Desenvolvido para**: Pesquisa em segmentação semântica com deep learning  \n'...
        '**Compatibilidade**: MATLAB R2019b+  \n'...
        '**Licença**: Acadêmica  \n'
    ];
    
    % Escrever README
    fid = fopen('README.md', 'w');
    if fid == -1
        error('Não foi possível atualizar README');
    end
    fprintf(fid, '%s', conteudo_readme);
    fclose(fid);
end